# Generated by Django 3.2.13 on 2022-06-06 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appone', '0003_auto_20220513_1639'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='active',
            field=models.BooleanField(default=1, verbose_name='Ativo'),
            preserve_default=False,
        ),
    ]
