# Generated by Django 3.2.13 on 2022-06-06 20:20

import appone.utils
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appone', '0004_question_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='active',
            field=appone.utils.MyBooleanField(verbose_name='Ativo'),
        ),
    ]
