# Generated by Django 3.2.13 on 2022-06-15 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appone', '0006_auto_20220615_1725'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='name',
            field=models.CharField(default='anonimo', max_length=200),
            preserve_default=False,
        ),
    ]
