# Generated by Django 3.2.13 on 2022-06-15 20:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appone', '0007_author_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='author',
            options={'verbose_name': 'Autor', 'verbose_name_plural': 'Autores'},
        ),
        migrations.AlterModelOptions(
            name='choice',
            options={'verbose_name': 'Opção', 'verbose_name_plural': 'Opções'},
        ),
        migrations.AlterModelOptions(
            name='profile',
            options={'verbose_name': 'Perfil de autor', 'verbose_name_plural': 'Perfis de autores'},
        ),
        migrations.AlterModelOptions(
            name='question',
            options={'verbose_name': 'Enquete', 'verbose_name_plural': 'Enquetes'},
        ),
        migrations.AlterModelOptions(
            name='tag',
            options={'verbose_name': 'Rótulo', 'verbose_name_plural': 'Rótulos'},
        ),
        migrations.AlterField(
            model_name='question',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='appone.author'),
        ),
        migrations.AlterField(
            model_name='question',
            name='tags',
            field=models.ManyToManyField(blank=True, to='appone.Tag', verbose_name='Tags'),
        ),
    ]
